spring.application.name=WalletProject
spring.datasource.url=jdbc:postgresql://localhost:5433/wallet
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.liquibase.enabled =true
spring.liquibase.change-log=classpath:db/changelog/changelog-master.yaml